server:
    port: 8080
    jetty:
        accesslog:
            enabled: true
            filename: logs/jetty-access.log
        max-http-form-post-size: 100MB
        threads.max: 200
        threads.min: 8
        threads.idle-timeout: 60000
spring:
    application:
        name: jpa-crud
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: admin
        driverClassName: org.postgresql.Driver
    flyway:
        enabled: true
        locations: classpath:db/migration
    jpa:
        hibernate:
            ddl-auto: validate # or none, since Flyway is managing schema
        show-sql: true
